DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS agents;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS repos;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
